### ISSUE TITLE
Firefox driver broken

### ISSUE THREAD

**Issue by mportesdev** [underground-lab/zelezobeton#3]
Instantiation of `selenium.webdriver.Firefox` raises an error:

```
>>> from selenium.webdriver import Firefox
>>> driver = Firefox()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[...]/selenium/webdriver/firefox/webdriver.py", line 177, in __init__
    super().__init__(
  File "[...]/selenium/webdriver/remote/webdriver.py", line 272, in __init__
    self.start_session(capabilities, browser_profile)
  File "[...]/selenium/webdriver/remote/webdriver.py", line 364, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "[...]/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "[...]/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1
```

and produces this error message:

![image](https://user-images.githubusercontent.com/43098013/196667737-8dd3b551-6c7c-4b0e-bb02-2b4f81c77e47.png)

This error breaks the `test_web_ui` test.

Python 3.10.8
selenium 4.5.0
geckodriver 0.32.0
Firefox 106.0 64bit (snap) on Ubuntu 22.04.1

**Comment by mportesdev** [comment]
The error is different in headless mode:

```
>>> from selenium.webdriver import Firefox
>>> from selenium.webdriver.firefox.options import Options
>>> options = Options()
>>> options.headless = True
>>> driver = Firefox(options=options)
[identical traceback]
selenium.common.exceptions.TimeoutException: Message: Failed to read marionette port
```

**Comment by mportesdev** [comment]
https://github.com/mozilla/geckodriver/issues/2010
